# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 705af39e76d5c1d691ba8479aa0a6700e1be20885c71dc09ff78cbb20d3b49242f3f7b03ce1d3a17d542ee8a2f0cec85f606addae8a4de4834b58d7c560ca9e1

test:
  secret_key_base: 0edd14e0b715998b3eb883cf8044cdb54d6b8cb89146195d664a4e26393f3b5bce2cf4e3860b7dc409e4fc9cd3da290ab980922155655d695f127f4745cdd498

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
